{
 "title": "Charm Status (WIP)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Monitored Models",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum by (juju_model) (up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Database size",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(1, sum by (instance, juju_model) (pg_database_size_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alerts that have been firing over the last 24 hours",
   "type": "table",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort_desc(sum(sum_over_time(ALERTS{alertstate=\"firing\"}[24h])) by (alertname,juju_model,juju_application))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}